### ISSUE TITLE
Dashboard scoreboard

### ISSUE THREAD

**Issue by Razano26** [Razano26/HardLoop#10]
Add a minecraft scoreboard, displayed on the sidebar.

In this scoreboard we would like to displays:
 - Time from last reset
 - Time played on this loop
 - Reset count
 - Player online / player on this loop

This scoreboard would be like [Hypixel scoreboard](https://preview.redd.it/ttpi4fo758y41.jpg?width=296&format=pjpg&auto=webp&s=9b2bc7330134573c0a551c8e506e7a025e5bd793)

**Comment by Nayrode** [comment]
we'll see for the last point, i will recreate an issue, for the moment, the first 2 points are done

**Comment by Nayrode** [comment]
see #12
